#!/usr/bin/env zsh

# -----------------------------------------------------------------------------
# "THE BEER-WARE LICENSE" (Revision 42):
# <bonecrusher@covenofchaos.com>  wrote this file.  As long as  you retain this
# notice you can do whatever you want with this stuff.  If we meet some day and
# you think this stuff is worth it, you can buy me a beer in return.
#  > BoneCrusher <
# -----------------------------------------------------------------------------
[[ -z $1 ]] && { echo "You must specify a config file"; exit -1; }

source $1

# VALIDATE CONFIG
curl -sL https://raw.githubusercontent.com/egalpin/apt-vim/master/install.sh | sh

for package in "${packages[@]}"
do
  echo 'installing ' "${package}"
  ~/.vimpkg/bin/apt-vim install -y "${package}" > /dev/null
done

(cd ~/.vimpkg/bundle/YouCompleteMe && git submodule update --init --recursive)
git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
git clone https://github.com/scrooloose/nerdtree.git ~/.vim/bundle/nerdtree
vim +PluginInstall +qall
